### ISSUE TITLE
リパーシェ表示の際に最も上の表示の大文字を全て小文字に置換すべき

### ISSUE THREAD

**Issue by Fafsfalira** [lemoncmd/lerssergyl#2]
意図的かはわからないんだけど、分解機で単語ごとに分けられたところでは強制的に小文字になっているんだけど、最も上の文章では大文字がそのまま反映されているからfがvhになったりするので、出来れば修正したい。

Mi firlex niv eso la lex feat co'st xelerl ol et pelx kranteerleffe veles aduarneo fal karsergol fai liparxe.

**Comment by Fafsfalira** [comment]
てか、表示上でfhと入力したらfъhで表示されるのはまずいな。かといってFで入力すると一番上の表示欄ではvhで表示されるが、分解機のここの表記では強制的に小文字化されてfになるのでこれもまずいな。オプションでフォントスペリングを読み込むか、一般的なラテン文字転写法を読み込むかの設定を設けてそれで分けたりできないだろうか。表示上だけ（辞書に対しては処理なしのスペリングを適用する必要がある）の話だが、前者は前処理なしに文字を読み込む（F,V,Xもそのままvh, fh, dzで表示される）、後者は強制的に小文字化し、一文字二転写文字を内部で処理してF, V, Xでフォント表示する。

**Comment by lemoncmd** [comment]
対応しました。Ketiven Liparxe部分に小文字化およびF,V,Xへの置換を適用し、そしてCirlxarli LiparxeのフォントをCilkurleen Cirlxarliに置き換えました。0.6.0リリース以降適用予定です。
