### ISSUE TITLE
ダークモードだと読みづらい

### ISSUE THREAD

**Issue by mizugane** [lemoncmd/lerssergyl#4]
Windows10の個人用設定>色を黒にしていると文字が薄いグレーになり、背景と同化して読みづらくなってしまう。つらみ。（色を白に変えたら黒字になりました）

![li](https://user-images.githubusercontent.com/49014508/86097901-53426900-baf0-11ea-8946-4badb58fd943.jpg)

**Comment by lemoncmd** [comment]
修正しました。修正は0.6.0リリース以降に適用されます。
