### ISSUE TITLE
altelが分解できない

### ISSUE THREAD

**Issue by Fafsfalira** [lemoncmd/lerssergyl#5]
詩語altに-elが付いたaltelが現状分解できていない。alt自体が表示されないので内部辞書の問題だと思われるが流石にユーザー側では切り分けできないので調べて欲しい。

**Comment by lemoncmd** [comment]
Xace fua co'd jostolo! Wioll 0.6.1te falvelta io la lex aduarne iniaziurgonj!
詳細：0.6.1の辞書更新によりaltが単語登録されていない状態が解消する予定です。
詳細の詳細：j.v氏の分解器の単語とLineparineJson（双方とも2017年）の時期が微妙にずれていることにより登録されなかった単語があり、分解器用の単語帳の自動生成ツールを作ったためこの状態が解消。
